### ISSUE TITLE
Contributor screen mods

### ISSUE THREAD

**Issue by mozesnjoroge** [omondibrian/Rada-Egerton#40]
Modify the arrow back button for backward navigation. Refer to rada_uon for fine details.

**Comment by Ashisoma** [comment]
Sawasawa, on it

**Comment by Ashisoma** [comment]
I am done with the editing on the back button and your full names

**Comment by mozesnjoroge** [comment]
Moses Ngure Njoroge
@ojayjonathan, @omondibrian, @saidmsaid81 comment on this issue with your full names

**Comment by Ashisoma** [comment]
I have already gotten their full names. On a later version, I was hoping in some way if the tile was tapped of a name it would lead them to one's email or ghub account.

**Comment by saidmsaid81** [comment]
> I have already gotten their full names. On a later version, I was hoping in some way if the tile was tapped of a name it would lead them to one's email or ghub account.

You have my full name too? Ama? By the way thats a good idea..

**Comment by Ashisoma** [comment]
> > I have already gotten their full names. On a later version, I was hoping in some way if the tile was tapped of a name it would lead them to one's email or ghub account.
> 
> You have my full name too? Ama? By the way thats a good idea..

yes I have gotten your full names from ghub

**Comment by Ashisoma** [comment]
I think this bug is out
